### ISSUE TITLE
404 on windows with a portable node

### ISSUE THREAD

**Issue by bckmnn** [fbrctr/fabricator#120]
Hi there,
i'd like to try out fabricator. i installed it on my work machine with a portable node.js version. when i do `npm start` everything looks fine. but opening localhost:3000 gets me a 404.
my dist folder contains the following:

```
drwxr-xr-x    4 Administ        0 Apr 17 06:27 assets
-rw-r--r--    1 Administ    37575 Apr 17 06:27 favicon.ico
drwxr-xr-x    3 Administ        0 Apr 17 06:27 src
```
when entering http://localhost:3000/src/views/index.html i get the index page with missing css an javascript. not sure why the fabrication is not working.

my fabricator output is like this: 

```
PS D:\__LibraryTest> npm start

> fabricator@1.1.1 prestart D:\__LibraryTest
> npm install


> fabricator@1.1.1 start D:\__LibraryTest
> gulp --dev

[08:27:26] Using gulpfile D:\__LibraryTest\gulpfile.js
[08:27:26] Starting 'clean'...
[08:27:26] Finished 'clean' after 15 ms
[08:27:26] Starting 'default'...
[08:27:26] Starting 'styles:fabricator'...
[08:27:26] Starting 'styles:toolkit'...
[08:27:26] Starting 'scripts'...
[08:27:26] Starting 'favicon'...
[08:27:26] Starting 'assemble'...
[08:27:26] Finished 'assemble' after 93 ms
[08:27:26] Finished 'default' after 112 ms
[08:27:28] Finished 'favicon' after 2.21 s
[08:27:28] Starting 'images'...
[08:27:28] gulp-imagemin: Minified 0 images
[08:27:28] Finished 'images' after 62 ms
[08:27:29] Finished 'styles:toolkit' after 2.56 s
[08:27:29] Finished 'styles:fabricator' after 2.56 s
[08:27:29] Starting 'styles'...
[08:27:29] Finished 'styles' after 4.85 µs
[08:27:29] Finished 'scripts' after 2.94 s
[08:27:29] Starting 'serve'...
[08:27:29] Finished 'serve' after 469 ms
[FABRICATOR] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://-:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://-:3001
 ------------------------------------
[FABRICATOR] Serving files from: dist
```

**Comment by LukeAskew** [comment]
You shouldn't be seeing `src` in your `dist` - it should just contain compiled assets.

Does it compile correctly when you run `npm run build` ?

**Comment by bckmnn** [comment]
hm nope output looks like above but still just asset and src folder in dist

**Comment by LukeAskew** [comment]
You could try inserting https://github.com/sindresorhus/gulp-debug in a task. `styles` would probably be easiest.

I've never used portable node. Can you point me in the right direction to try and duplicate this issue.

**Comment by bckmnn** [comment]
Ok, i did the gulp debug thing, which revealed nothing interesting to me. Here the output:

```
PS D:\__LibraryTest> npm run build

> fabricator@1.1.1 build D:\__LibraryTest
> npm install && gulp

[11:40:02] Using gulpfile D:\__LibraryTest\gulpfile.js
[11:40:02] Starting 'clean'...
[11:40:03] Finished 'clean' after 341 ms
[11:40:03] Starting 'default'...
[11:40:03] Starting 'styles:fabricator'...
[11:40:03] Starting 'styles:toolkit'...
[11:40:03] Starting 'scripts'...
[11:40:03] Starting 'favicon'...
[11:40:03] Starting 'assemble'...
[11:40:03] Finished 'assemble' after 79 ms
[11:40:03] Finished 'default' after 135 ms
[11:40:03] debug-styles:toolkit: src\assets\toolkit\styles\toolkit.css
[11:40:03] debug-styles:toolkit: 1 items
[11:40:03] debug-styles:fabricator: src\assets\fabricator\styles\f.css
[11:40:03] debug-styles:fabricator: 1 items
[11:40:03] Finished 'favicon' after 302 ms
[11:40:03] Starting 'images'...
[11:40:03] gulp-imagemin: Minified 0 images
[11:40:03] Finished 'images' after 5.15 ms
[11:40:04] Finished 'styles:toolkit' after 1.28 s
[11:40:04] Finished 'styles:fabricator' after 1.32 s
[11:40:04] Starting 'styles'...
[11:40:04] Finished 'styles' after 3.99 µs
[11:40:05] Finished 'scripts' after 1.9 s
```

I figured since the styles tasks looks like its working fine, it could be some issue with the assemble task. So i tried to run the tests for fabricator-assemble. I got the following output:

```
PS D:\__LibraryTest\node_modules\fabricator-assemble> mocha


  fabricator-assemble
    1) should assemble a template
    2) should assemble docs
    3) should assemble user-created views
    4) should assemble with layout includes
    5) should assemble with helpers


  0 passing (186ms)
  5 failing

  1) fabricator-assemble should assemble a template:
     ENOENT, no such file or directory 'D:\__LibraryTest\node_modules\fabricator
-assemble\test\output\index.html'
      at Object.fs.openSync (fs.js:439:18)
      at Object.fs.readFileSync (fs.js:290:15)

  2) fabricator-assemble should assemble docs:
     ENOENT, no such file or directory 'D:\__LibraryTest\node_modules\fabricator
-assemble\test\output\docs.html'
      at Object.fs.openSync (fs.js:439:18)
      at Object.fs.readFileSync (fs.js:290:15)

  3) fabricator-assemble should assemble user-created views:
     ENOENT, no such file or directory 'D:\__LibraryTest\node_modules\fabricator
-assemble\test\output\pages\home.html'
      at Object.fs.openSync (fs.js:439:18)
      at Object.fs.readFileSync (fs.js:290:15)

  4) fabricator-assemble should assemble with layout includes:
     ENOENT, no such file or directory 'D:\__LibraryTest\node_modules\fabricator
-assemble\test\output\includes.html'
      at Object.fs.openSync (fs.js:439:18)
      at Object.fs.readFileSync (fs.js:290:15)

  5) fabricator-assemble should assemble with helpers:
     ENOENT, no such file or directory 'D:\__LibraryTest\node_modules\fabricator
-assemble\test\output\helpers.html'
      at Object.fs.openSync (fs.js:439:18)
      at Object.fs.readFileSync (fs.js:290:15)
```

however there is a `test\output\test\fixtures\views` folder containing nicely renderd html pages. so i guess its a path thing in fabricator-assemble.

**Comment by bckmnn** [comment]
found the issue .. apparently path.dirname(file) does not return a path with the os path seperator, but one with standard slashes. when changing line [486 of index.js](https://github.com/fbrctr/fabricator-assemble/blob/master/index.js#L486) to the following everything works fine:
```
		var dirname = path.normalize(path.dirname(file)).split(path.sep).pop(),
```

**Comment by LukeAskew** [comment]
Good find. Thanks!

**Comment by bckmnn** [comment]
Just tested 1.1.2 assembly works fine, but the links in the html are still referencing the `src/views/...` folder, i updated my comment yesterday it's all occurences of `path.dirname()` that need to be normalized.

**Comment by LukeAskew** [comment]
Working on this. FYI https://github.com/fbrctr/fabricator-assemble/issues/2
