### ISSUE TITLE
Fabricator runs and creates a style guide, but does throw an error in the console and does not load images to 'dist'

### ISSUE THREAD

**Issue by herince** [fbrctr/fabricator#122]
This is what is being logged to the console when I run <code>npm start</code>:

    [19:50:37] Starting 'assemble'...
    [19:50:38] 'assemble' errored after 138 ms
    [19:50:38] Error: The partial paragraph could not be found
    at new Error (<anonymous>)
    at Error.Exception (c:\xampp\htdocs\styleguide-draft\node_modules\fabricator-assemble\node_modules\handlebars\dist\cjs\handlebars\exception.js:13:41)
    at Object.invokePartial (c:\xampp\htdocs\styleguide-draft\node_modules\fabricator-assemble\node_modules\handlebars\dist\cjs\handlebars\runtime.js:179:11)
    at Object.invokePartialWrapper [as invokePartial] (c:\xampp\htdocs\styleguide-draft\node_modules\fabricator-assemble\node_modules\handlebars\dist\cjs\handlebars\runtime.js:46:39)
    at Object.eval (eval at <anonymous> (c:\xampp\htdocs\styleguide-draft\node_modules\fabricator-assemble\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:171:23), <anonymous>:25:17)
    at ret (c:\xampp\htdocs\styleguide-draft\node_modules\fabricator-assemble\node_modules\handlebars\dist\cjs\handlebars\runtime.js:137:30)
    at ret (c:\xampp\htdocs\styleguide-draft\node_modules\fabricator-assemble\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:422:21)
    at c:\xampp\htdocs\styleguide-draft\node_modules\fabricator-assemble\index.js:505:30
    at Array.forEach (native)
    at assemble (c:\xampp\htdocs\styleguide-draft\node_modules\fabricator-assemble\index.js:481:8)

I have not changed the image paths in the gulpfile.

P.S. I also noticed this:
![footer](https://cloud.githubusercontent.com/assets/7620254/7257818/01151dc4-e861-11e4-9df7-c9fe1a4ac9cb.png)
for footer.html with content <code>\<div class="footer">\</div></code> (it is in a folder with other components, that are look just fine). Any idea why this might be happening?

**Comment by LukeAskew** [comment]
This is a little bit of a bug. On the initial compile, if the `assemble` task doesn't complete, other tasks (like `images`) can he halted.

The reason `assemble` is failing is because the `paragraph` material was either moved or deleted, but is still being referenced in a view or other material.

If you deleted `paragraph.html` then you need to also delete any references to it. Out of the box, it is used in the `materials/structures/form.html` example.

**Comment by herince** [comment]
Can I delete an issue (because ot it's non-issue-ness)? :D

P.S. Fixed everything. Thanx! (and I'm sorry for the stupid questions)

**Comment by LukeAskew** [comment]
:+1: np. There's a good chance someone else has the same questions.
