### ISSUE TITLE
Start script failing

### ISSUE THREAD

**Issue by Lianzinho** [fbrctr/fabricator#144]
Hey guys, the second part of the start script is failing, specifically when `gulp --dev` is run.

The error messages:

```node
$ npm start

> fabricator@1.2.1 prestart /Applications/MAMP/htdocs/nature
> npm install


> fabricator@1.2.1 start /Applications/MAMP/htdocs/nature
> gulp --dev


fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Applications/MAMP/htdocs/nature/node_modules/browser-sync/node_modules/browser-sync-ui/static/content/help.content.html'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at fileContent (/Applications/MAMP/htdocs/nature/node_modules/browser-sync/node_modules/browser-sync-ui/lib/plugins/help/help.plugin.js:48:26)
    at Object.<anonymous> (/Applications/MAMP/htdocs/nature/node_modules/browser-sync/node_modules/browser-sync-ui/lib/plugins/help/help.plugin.js:15:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

npm ERR! fabricator@1.2.1 start: `gulp --dev`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the fabricator@1.2.1 start script.
npm ERR! This is most likely a problem with the fabricator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls fabricator
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Applications/MAMP/htdocs/nature
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.26
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Applications/MAMP/htdocs/nature/npm-debug.log
npm ERR! not ok code 0
```

Any tips on how to solve that?

Thanks

**Comment by LukeAskew** [comment]
Looks like an issue with the BrowserSync module. 

Start by deleting `node_modules/browser-sync` and trying again.

You may also want to update npm. You're on v1.4 and the current is v.2.12. Some dependencies may require v2 apis.
