### ISSUE TITLE
Error while having a numbered/hyphen containing components folder

### ISSUE THREAD

**Issue by ovlb** [fbrctr/fabricator#173]
I’ve added a folder called «002-type» to my components folder. Now i get the following error message when i modify/save a file:
```
[20:29:34] Starting 'assemble'...
Error (fabricator-assemble): You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined
 Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined
    at Object.compile (/path/to/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:464:11)
    at HandlebarsEnvironment.hb.compile (/path/to/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars.js:38:41)
    at Object.<anonymous> (/path/to/node_modules/fabricator-assemble/index.js:560:20)
    at Object.eval (eval at createFunctionContext (/path/to/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:7:78)
    at ret (/path/to/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/path/to/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Object.invokePartial (/path/to/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)
    at Object.invokePartialWrapper [as invokePartial] (/path/to/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (/path/to/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:12:23)
    at prog (/path/to/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
[20:29:34] Finished 'assemble' after 98 ms
```

The server is still up and running. Until i rename the folder, e.g. to «type». After that npm quits and shows the following error message (this is the content of npm_debug.log in the fabricator root):
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.3
3 info using node@v4.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart fabricator@1.2.2
6 verbose unsafe-perm in lifecycle true
7 info start fabricator@1.2.2
8 verbose unsafe-perm in lifecycle true
9 info fabricator@1.2.2 Failed to exec start script
10 verbose stack Error: fabricator@1.2.2 start: `gulp --dev`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:817:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid fabricator@1.2.2
12 verbose cwd /Volumes/Library/Development/ovlb/Website/_code/ovlb-fbrctr
13 error Darwin 14.5.0
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
15 error node v4.1.0
16 error npm  v2.14.3
17 error code ELIFECYCLE
18 error fabricator@1.2.2 start: `gulp --dev`
18 error Exit status 1
19 error Failed at the fabricator@1.2.2 start script 'gulp --dev'.
19 error This is most likely a problem with the fabricator package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     gulp --dev
19 error You can get their info via:
19 error     npm owner ls fabricator
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

When i ```npm start``` without a folder containing hyphens (or underscores) everything runs okay.
Any ideas what could have gone wrong? Unfortunately, i’m quite new to working with NPM and have no clue where i could look for solutions.

Regards,
O

P.S. Nonetheless you built a pretty great tool! Thanks!

**Comment by LukeAskew** [comment]
Hmm. Not sure. Are there `.html` files in that `002-type` directory?

The error makes me think something in those files is malformed.

**Comment by ovlb** [comment]
Ah, sorry. Got a head full of work and just being reminded of this. There were .html files in the folder, yes. However they were parsed without further problems after i’ve removed them from the folder and just prefixed them with 002.001, 002.002 and so forth.
