### ISSUE TITLE
templates not finding partials in subfolders within materials directory

### ISSUE THREAD

**Issue by leecsargent** [fbrctr/fabricator#174]
I just recently realized I could organize materials in categories by placing them in subdirectories, ie there can be many lists, tables, etc. So they are now in materials/modules/subdirectory.  That works great for creating what is now modules.html.  The issue I'm having now is that templates within views/templates don't find those partials, since they are not at the root of the modules directory.  

```
Error (fabricator-assemble): The partial asset-promo-image could not be found
 Error: The partial asset-promo-image could not be found
    at Object.invokePartial (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:216:11)
    at Object.invokePartialWrapper [as invokePartial] (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:16:23)
    at ret (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at /Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/index.js:638:30
    at Array.forEach (native)
    at assemble (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/index.js:606:8)
    at module.exports (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/index.js:663:3)
    at Gulp.<anonymous> (/Users/lsargent/Code/fabricator/gulpfile.js:156:5)
Error (fabricator-assemble): The partial asset-promo-image could not be found
 Error: The partial asset-promo-image could not be found
    at Object.invokePartial (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:216:11)
    at Object.invokePartialWrapper [as invokePartial] (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:16:23)
    at ret (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at /Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/index.js:638:30
    at Array.forEach (native)
    at assemble (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/index.js:606:8)
    at module.exports (/Users/lsargent/Code/fabricator/node_modules/fabricator-assemble/index.js:663:3)
    at Gulp.<anonymous> (/Users/lsargent/Code/fabricator/gulpfile.js:156:5)

**Comment by LukeAskew** [comment]
Try accessing them using dot notation.

i.e. `materials/modules/subdirectory/asset-promo-image.html` -> `{{> subdirectory.asset-promo-image}}`

**Comment by leecsargent** [comment]
Ah! Thanks so much.
