### ISSUE TITLE
Ordering materials at the third sub level doesn't work

### ISSUE THREAD

**Issue by alienlebarge** [fbrctr/fabricator#212]
I have some difficulties to order materials.
Everything is fine when I'm ordering level 2 materials like the example below.

```
src/materials
├── atoms
│   ├── 01-headings
│   │   ├── heading-level-1.html
│   │   ├── heading-level-2.html
│   │   ├── heading-level-3.html
│   │   ├── heading-level-4.html
│   │   ├── heading-level-5.html
│   │   ├── heading-level-6.html
│   │   └── helper-classes.html
│   ├── 02-paragraph.html
│   ├── 03-inline-text
│   │   └── ...
│   └── ...
└── ...
```

But when I try to order some level 3 items things get complicated.

```
src/materials
├── atoms
│   ├── 01-headings
│   │   ├── 01-heading-level-1.html
│   │   ├── 02-heading-level-2.html
│   │   ├── 03-heading-level-3.html
│   │   ├── 04-heading-level-4.html
│   │   ├── 05-heading-level-5.html
│   │   ├── 06-heading-level-6.html
│   │   └── 07-helper-classes.html
│   ├── 02-paragraph.html
│   ├── 03-inline-text
│   │   └── ...
│   └── ...
└── ...
```

Here's the error I get in Terminal

```
[16:25:59] Starting 'assemble'...
Error (fabricator-assemble): You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined
 Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined
    at Object.compile (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:464:11)
    at HandlebarsEnvironment.hb.compile (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars.js:38:41)
    at Object.<anonymous> (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/index.js:560:20)
    at Object.eval (eval at createFunctionContext (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:7:78)
    at Object.ret (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at Object.ret [as f-item-content] (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Object.invokePartialWrapper [as invokePartial] (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:65:46)
    at Object.eval (eval at createFunctionContext (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:12:23)
    at prog (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at execIteration (/Users/cedricaellen/Projects/foehn/node_modules/fabricator-assemble/node_modules/handlebars/dist/cjs/handlebars/base.js:155:19)
```

**Comment by LeBenLeBen** [comment]
It looks like this issue is coming from the regex that remove the digit prefixes from the file name to create the Handlebar template.

```
name.replace(/^([a-z][a-z0-9\-]*\.)?([0-9\.-]+)(.*)$/i, '$1$3');
```

As you can see [here](http://regexr.com/3cbh0), this target only the prefix once and if it’s at the beginning of the key.

Changing this line to something like `name.replace(/(\d+[\-\.]{0,1})+/ig, '')` which will replace all occurrences, wherever they are in the string as you can see [here](http://regexr.com/3cbh3) seems to fix the issue for me.

What do you think @LukeAskew ?

**Comment by alienlebarge** [comment]
@LukeAskew the change has been made by @LeBenLeBen (thanks to him) in fbrctr/fabricator-assemble#31

Any idea when fabricator-assemble will be in 1.1.10 to get this fix via npm ?

**Comment by LukeAskew** [comment]
published!
