### ISSUE TITLE
New materials don't show up

### ISSUE THREAD

**Issue by velvetlicious** [fbrctr/fabricator#222]
I'm having problems adding new materials. I added a new folder called "molecules" on the materials folder, then created a new html called molecules.html on the views folder, etc.

The new materials shows up in the navigation menu, but when I click on them I get this error "Cannot get /molecules.html" though the file is in there.

I checked the dist folder, and the new files are not being build

I get this error on the console:

[10:56:57] Using gulpfile ~/Sites/styleguide-fb/gulpfile.js
[10:56:57] Starting 'clean'...
[10:56:57] Finished 'clean' after 12 ms
[10:56:57] Starting 'default'...
[10:56:57] Starting 'styles:fabricator'...
[10:56:57] Finished 'styles:fabricator' after 11 ms
[10:56:57] Starting 'styles:toolkit'...
[10:56:57] Finished 'styles:toolkit' after 1.92 ms
[10:56:57] Starting 'styles'...
[10:56:57] Finished 'styles' after 17 μs
[10:56:57] Starting 'scripts'...
[10:56:57] Starting 'favicon'...
[10:56:57] Starting 'assemble'...
Error (fabricator-assemble): The partial text-input could not be found
 Error: The partial text-input could not be found
    at Object.invokePartial (/Users/tannia/Sites/styleguide-fb/node_modules/handlebars/dist/cjs/handlebars/runtime.js:216:11)
    at Object.invokePartialWrapper [as invokePartial] (/Users/tannia/Sites/styleguide-fb/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (/Users/tannia/Sites/styleguide-fb/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:6:23)
    at ret (/Users/tannia/Sites/styleguide-fb/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/Users/tannia/Sites/styleguide-fb/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Object.<anonymous> (/Users/tannia/Sites/styleguide-fb/node_modules/fabricator-assemble/index.js:566:23)
    at Object.eval (eval at createFunctionContext (/Users/tannia/Sites/styleguide-fb/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:7:78)
    at ret (/Users/tannia/Sites/styleguide-fb/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/Users/tannia/Sites/styleguide-fb/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Object.invokePartial (/Users/tannia/Sites/styleguide-fb/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)
[10:56:58] Finished 'assemble' after 184 ms
[10:56:58] Finished 'default' after 213 ms
[10:56:58] Finished 'favicon' after 358 ms
[10:56:58] Starting 'images'...
[10:56:58] gulp-imagemin: Minified 0 images
[10:56:58] Finished 'images' after 4.32 ms
[10:56:58] Finished 'scripts' after 854 ms
[10:56:58] Starting 'serve'...
[10:56:58] Finished 'serve' after 65 ms
[FABRICATOR] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.5.0.45:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.5.0.45:3001
 ----------------------------------
[FABRICATOR] Serving files from: dist

I'm not sure what to do to fix this. Please help.

**Comment by LukeAskew** [comment]
Looks like the error `Error (fabricator-assemble): The partial text-input could not be found` is what might be the issue.

The `{{> text-input}}` partial include is used on the `materials/structures/form.html` example out of the box. If you delete the `text-input.html` file in `structures`, then you'll need to remove this reference.
