### ISSUE TITLE
Partial Error

### ISSUE THREAD

**Issue by jonorherrington** [fbrctr/fabricator#223]
I have an issue in the latest release of Fabricator that I have not seen before. When I delete the paragraph.html partial under components or the form.html partial under structures I get the error displayed below (please note when it's paragraph missing the error reads The partial paragraph could not be found). Any ideas?

Error: The partial form could not be found
    at Object.invokePartial (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/handlebars/dist/cjs/handlebars/runtime.js:216:11)
    at Object.invokePartialWrapper [as invokePartial] (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:16:23)
    at ret (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at /Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/fabricator-assemble/index.js:638:30
    at Array.forEach (native)
    at assemble (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/fabricator-assemble/index.js:606:8)
    at module.exports (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/fabricator-assemble/index.js:663:3)
    at Gulp.<anonymous> (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/gulpfile.js:167:2)
    at module.exports (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/gulp/index.js:36:18)
    at Gaze.<anonymous> (/Users/jherrington/Desktop/dev/hdr-dwre-website/style-guide/node_modules/glob-watcher/index.js:18:14)

**Comment by jonorherrington** [comment]
I'm stupid ... the end ...

**Comment by LukeAskew** [comment]
For those that come behind you... was it orphaned `{{> paragraph}}` in some view/partial ?

**Comment by jonorherrington** [comment]
Yeah so in the page.html file there was an include for the paragraph and form partial. This leads me to ask is it the best idea to be calling those within the view
