### ISSUE TITLE
assemble task helper-markdown issue

### ISSUE THREAD

**Issue by danmv** [fbrctr/fabricator#275]
Hi, 
I keep on getting this error 

`[10:15:47] Error: Cannot find module 'helper-markdown'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Gulp.<anonymous> (C:\development\expd-fabricator\gulpfile.js:118:14)
    at module.exports (C:\development\expd-fabricator\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\development\expd-fabricator\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\development\expd-fabricator\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at C:\development\expd-fabricator\node_modules\gulp\node_modules\orchestrator\index.js:279:18
    at finish (C:\development\expd-fabricator\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
`
how can i fix it?

**Comment by LukeAskew** [comment]
Try reinstalling/upgrading your node_modules.
