### ISSUE TITLE
Dependencies fail to install under node v0.10.32

### ISSUE THREAD

**Issue by couto** [fbrctr/fabricator#77]
I didn't delve to deep to see why, but I can get this behaviour consistently on computers (Ubuntu Trusty 64 and OSX 10.9.5) using node v0.10.32, (also tested with npm v2.0.2. and v1.4.28)

```
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/Users/couto/.nvm/v0.10.32/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.0.2
npm ERR! path /Users/couto/.npm/f9748a33-adable-stream-1-0-32-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47

npm ERR! EEXIST, open '/Users/couto/.npm/f9748a33-adable-stream-1-0-32-package-tgz.lock'
File exists: /Users/couto/.npm/f9748a33-adable-stream-1-0-32-package-tgz.lock
Move it away, and try again.

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/Users/couto/.nvm/v0.10.32/bin/npm" "run" "dev"
npm ERR! node v0.10.32
npm ERR! npm  v2.0.2
npm ERR! code ELIFECYCLE
npm ERR! fabricator@0.6.0 dev: `npm install && gulp dev`
npm ERR! Exit status 47
npm ERR!
npm ERR! Failed at the fabricator@0.6.0 dev script.
npm ERR! This is most likely a problem with the fabricator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && gulp dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls fabricator
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/couto/Development/[REDACTED]/[REDACTED]/npm-debug.log
```

and the npm-debug.log contents:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/Users/couto/.nvm/v0.10.32/bin/npm', 'run', 'dev' ]
2 info using npm@2.0.2
3 info using node@v0.10.32
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev fabricator@0.6.0
6 info dev fabricator@0.6.0
7 verbose unsafe-perm in lifecycle true
8 info fabricator@0.6.0 Failed to exec dev script
9 verbose stack Error: fabricator@0.6.0 dev: `npm install && gulp dev`
9 verbose stack Exit status 47
9 verbose stack     at ChildProcess.<anonymous> (/Users/couto/.nvm/v0.10.32/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:756:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
10 verbose pkgid fabricator@0.6.0
11 verbose cwd /Users/couto/Development/[REDACTED]/[REDACTED]
12 error Darwin 13.4.0
13 error argv "node" "/Users/couto/.nvm/v0.10.32/bin/npm" "run" "dev"
14 error node v0.10.32
15 error npm  v2.0.2
16 error code ELIFECYCLE
17 error fabricator@0.6.0 dev: `npm install && gulp dev`
17 error Exit status 47
18 error Failed at the fabricator@0.6.0 dev script.
18 error This is most likely a problem with the fabricator package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm install && gulp dev
18 error You can get their info via:
18 error     npm owner ls fabricator
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

If you need more information, please feel free to ask.

edit: Redacted some names to avoid google searches

**Comment by mikeputnam** [comment]
This is resolved by upgrading your npm: https://github.com/npm/npm/issues/6309
